site_name: タスク管理アプリ Documentation
site_description: Cloudflare WorkersとNext.jsを使用したタスク管理アプリケーション
site_author: taskm team
site_url: https://taskm.pages.dev

repo_name: hrfm1623/taskm
repo_url: https://github.com/hrfm1623/taskm

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - ホーム: index.md
  - アーキテクチャ: architecture.md
  - API仕様: api.md
  - 開発ガイド:
    - セットアップ: development/setup.md
    - 開発フロー: development/workflow.md
    - テスト: development/testing.md
  - デプロイメント: deployment.md