name = "taskm"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm build:pages"

[build.upload]
format = "service-worker"

pages_build_output_dir = "frontend/.vercel/output/static" 