compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd frontend && pnpm install && pnpm pages:build"
cwd = "frontend"

[build.output]
directory = "frontend/.vercel/output/static"

[pages]
pages_build_output_dir = "frontend/.vercel/output/static"