compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

[build.upload]
format = "service-worker"

[pages]
pages_build_output_dir = ".vercel/output/static"