compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd frontend && pnpm install && pnpm build"
cwd = "frontend"

[build.output]
directory = "frontend/.next"

[pages]
pages_build_output_dir = "frontend/.next"