name = "taskm-api"
main = "src/index.ts"
compatibility_date = "2023-12-30"

[vars]
ENV = "development"

[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "taskm-db"
database_id = "f50a2349-3841-423f-9fae-7e167b6190cd"

[build]
command = "pnpm prisma generate"

[env.production]
vars = { ENV = "production" }
d1_databases = [
  { binding = "DB", database_name = "taskm-db", database_id = "f50a2349-3841-423f-9fae-7e167b6190cd" }
] 