name = "twilight-mouse-9823"
main = "src/index.ts"
compatibility_date = "2023-12-30"
compatibility_flags = ["nodejs_compat"]

[vars]
ENV = "development"

[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "taskm-db"
database_id = "f50a2349-3841-423f-9fae-7e167b6190cd"

[env.production]
vars = { ENV = "production" }
d1_databases = [
  { binding = "DB", database_name = "taskm-db", database_id = "f50a2349-3841-423f-9fae-7e167b6190cd" }
] 

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true